### ISSUE TITLE
Can't predict forward with a non-positive rate of change on a map table

### ISSUE THREAD

**Issue by jcjones** [letsencrypt/mariadb-sequential-partition-manager-py#26]
Caught in dev in a table with a two-column primary key:

```
Traceback (most recent call last):
  File "/usr/local/bin/partition-manager", line 11, in <module>
    load_entry_point('mariadb-sequential-partition-manager==0.2.2', 'console_scripts', 'partition-manager')()
  File "/usr/lib/python3/dist-packages/partitionmanager/cli.py", line 466, in main
    raise e
  File "/usr/lib/python3/dist-packages/partitionmanager/cli.py", line 452, in main
    output = args.func(args)
  File "/usr/lib/python3/dist-packages/partitionmanager/cli.py", line 184, in partition_cmd
    return do_partition(conf)
  File "/usr/lib/python3/dist-packages/partitionmanager/cli.py", line 323, in do_partition
    sql_cmds = pm_tap.get_pending_sql_reorganize_partition_commands(
  File "/usr/lib/python3/dist-packages/partitionmanager/table_append_partition.py", line 658, in get_pending_sql_reorganize_partition_commands
    partition_changes = _plan_partition_changes(
  File "/usr/lib/python3/dist-packages/partitionmanager/table_append_partition.py", line 444, in _plan_partition_changes
    start_of_fill_time = _predict_forward_time(
  File "/usr/lib/python3/dist-packages/partitionmanager/table_append_partition.py", line 330, in _predict_forward_time
    raise ValueError(
ValueError: Can't predict forward with a non-positive rate of change: -1.4066321096499514 / [0.9769211071793219, -1.4066321096499514]
```

**Comment by jcjones** [comment]
Probably can be closed with #64 removing support
